# Default configuration for audio to text adapter training

# Mode: train or inference
mode: "train"

# Model settings
text_model_name: "BAAI/bge-m3"
audio_dim: 384
bottleneck_dim: 128

# Data settings
data_path: "path/to/your/orcahello_data.parquet"
output_path: "./outputs"

# Training hyperparameters
learning_rate: 0.005
batch_size: 256
num_workers: 4
max_epochs: 100
gradient_accumulation_steps: 1

# Data split settings
validation_start_date: "2023-01-01"

# PyTorch Lightning Trainer settings
accelerator: "auto"
devices: -1
strategy: "deepspeed"
precision: "bf16-mixed"

# Callbacks
early_stopping_patience: 3

# # Model checkpointing
# checkpoint_filename: "best-checkpoint"
# save_adapter_format: "pth"  # or "safetensors"

